parameters:
    api_key: '%env(API_KEY)%'
    api_version: '%env(API_VERSION)%'
    api_url: '%env(API_URL)%'
    api_database_id: '%env(API_DATABASE_ID)%'
    file_directory: '%kernel.project_dir%/public/uploads/cv'

services:
    _defaults:
        autowire: true 
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
